pipeline {
	agent any
	stages {
          stage('Deploy Blue Zone') {
              steps {
                withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
                  sh '''
		    kubectl apply -f release-controller-blue-zone.json
                  '''
                }
              }
           }
	   
	   stage('Direct to Blue Zone') {
		steps {
			withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
				sh '''
					kubectl apply -f lb-service-direct-blue-zone.json
				'''
			}
		}
	   }
	   stage('Redirect Traffic To Green Zone?') {
		    steps {
			input "Redirect Traffic To Green Zone?"
		    }
           }
	   stage('Deploy Green Zone') {
              steps {
                withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
                  sh '''
		    kubectl apply -f release-controller-green-zone.json
                  '''
                }
              }
           }

	   stage('Direct to Green Zone') {
		    steps {
			withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
				sh '''
					kubectl apply -f lb-service-direct-green-zone.json
				'''
			}
		    }
	 }
   }
}
