pipeline {
	agent any
	stages {
		stage('Test User Approval (4 Eyes , Segregation of Duty etc.') {
			    steps {
				input "Would you like to create the cluster?"
			    }
		}
		stage('Create k8s cluster') {
			steps {
				withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
					sh '''
						eksctl create cluster \
						--name app-cluster \
						--version 1.13 \
						--nodegroup-name standard-workers \
						--node-type t2.micro \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto
					'''
				}
			}
        	}
		stage('Create app-cluster conf') {
			steps {
				withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
					sh '''
						aws eks --region ap-southeast-1 update-kubeconfig --name app-cluster
					'''
				}
			}
		}
		stage('Test k8s cluster') {
			steps {
				withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
					sh 'kubectl get nodes # if we see our 2 nodes, we know we have authenticated correctly'
				}
			}
		}
		stage('Set current kubectl context') {
			steps {
				withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
					sh '''
						kubectl config use-context arn:aws:eks:ap-southeast-1:423966027140:cluster/app-cluster
					'''
				}
			}
		}
		stage('Delete Cluster Checkpoint') {
			    steps {
				input "Would you like to delete the cluster?"
			    }
		}
		stage('Delete k8s cluster') {
			steps {
				withAWS(region:'ap-southeast-1', credentials:'aws-k8s-adm') {
					sh 'eksctl delete cluster --name=app-cluster'
				}
			}
		}
	}
}
     
